// Skills dataset: image URLs + display names for the atlas
export const SKILLS = [
  { url: "/images/skills/aws.webp", name: "AWS" },
  { url: "/images/skills/css3.webp", name: "CSS3" },
  { url: "/images/skills/docker.webp", name: "Docker" },
  { url: "/images/skills/dynamodb.webp", name: "DynamoDB" },
  { url: "/images/skills/expo.webp", name: "Expo" },
  { url: "/images/skills/express.webp", name: "Express" },
  { url: "/images/skills/figma.webp", name: "Figma" },
  { url: "/images/skills/framer-motion.webp", name: "Framer Motion" },
  { url: "/images/skills/git.webp", name: "Git" },
  { url: "/images/skills/graphql.webp", name: "GraphQL" },
  { url: "/images/skills/gsap.webp", name: "GSAP" },
  { url: "/images/skills/html.webp", name: "HTML" },
  { url: "/images/skills/jest.webp", name: "Jest" },
  { url: "/images/skills/js.webp", name: "JavaScript" },
  { url: "/images/skills/mongo.webp", name: "MongoDB" },
  { url: "/images/skills/nextjs.webp", name: "Next.js" },
  { url: "/images/skills/node.webp", name: "Node.js" },
  { url: "/images/skills/playwrite.webp", name: "Playwright" },
  { url: "/images/skills/react three fiber.webp", name: "React Three Fiber" },
  { url: "/images/skills/react-hook-form.webp", name: "React Hook Form" },
  { url: "/images/skills/react-native.webp", name: "React Native" },
  { url: "/images/skills/react-query.webp", name: "React Query" },
  { url: "/images/skills/react.webp", name: "React" },
  { url: "/images/skills/redux.webp", name: "Redux" },
  { url: "/images/skills/sass.webp", name: "Sass" },
  { url: "/images/skills/storybook.webp", name: "Storybook" },
  { url: "/images/skills/tailwind.webp", name: "Tailwind CSS" },
  { url: "/images/skills/threejs.webp", name: "Three.js" },
  { url: "/images/skills/ts.webp", name: "TypeScript" },
  { url: "/images/skills/ui.webp", name: "UI" },
  { url: "/images/skills/vitest.webp", name: "Vitest" },
  { url: "/images/skills/zustand.webp", name: "Zustand" },
];
