// Skills dataset: image URLs + display names for the atlas
export const SKILLS = [
  { url: "/images/skills/aws.jpg", name: "AWS" },
  { url: "/images/skills/css3.jpg", name: "CSS3" },
  { url: "/images/skills/docker.jpg", name: "Docker" },
  { url: "/images/skills/dynamodb.jpg", name: "DynamoDB" },
  { url: "/images/skills/expo.jpg", name: "Expo" },
  { url: "/images/skills/express.jpg", name: "Express" },
  { url: "/images/skills/figma.jpg", name: "Figma" },
  { url: "/images/skills/framer-motion.jpg", name: "Framer Motion" },
  { url: "/images/skills/git.jpg", name: "Git" },
  { url: "/images/skills/graphql.jpg", name: "GraphQL" },
  { url: "/images/skills/gsap.jpg", name: "GSAP" },
  { url: "/images/skills/html.jpg", name: "HTML" },
  { url: "/images/skills/jest.jpg", name: "Jest" },
  { url: "/images/skills/js.jpg", name: "JavaScript" },
  { url: "/images/skills/mongo.jpg", name: "MongoDB" },
  { url: "/images/skills/nextjs.jpg", name: "Next.js" },
  { url: "/images/skills/node.jpg", name: "Node.js" },
  { url: "/images/skills/playwrite.jpg", name: "Playwright" },
  { url: "/images/skills/react three fiber.jpg", name: "React Three Fiber" },
  { url: "/images/skills/react-hook-form.jpg", name: "React Hook Form" },
  { url: "/images/skills/react-native.jpg", name: "React Native" },
  { url: "/images/skills/react-query.jpg", name: "React Query" },
  { url: "/images/skills/react.jpg", name: "React" },
  { url: "/images/skills/redux.jpg", name: "Redux" },
  { url: "/images/skills/sass.jpg", name: "Sass" },
  { url: "/images/skills/storybook.jpg", name: "Storybook" },
  { url: "/images/skills/tailwind.jpg", name: "Tailwind CSS" },
  { url: "/images/skills/threejs.jpg", name: "Three.js" },
  { url: "/images/skills/ts.jpg", name: "TypeScript" },
  { url: "/images/skills/ui.jpg", name: "UI" },
  { url: "/images/skills/vitest.jpg", name: "Vitest" },
  { url: "/images/skills/zustand.jpg", name: "Zustand" },
];
