/* eslint-disable @typescript-eslint/no-explicit-any */
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./public/model/confiancelabs/confiancelabs_model.gltf -k 
*/

import { CameraControls, useGLTF, useTexture } from "@react-three/drei";
import { angle } from "../../../utils";
import { useEffect, useRef, useMemo } from "react";
import * as THREE from "three";
import useConfianceStore, { type ConfianceCameraTypes } from "../../store/confianceStore";
import { FrameHtml } from "./Frame/FrameHtml";
import { TvHtml } from "./TV/TvHtml";
import { KioskHtml } from "./Kiosk/KioskHtml";
import { KdsHtml } from "./KDS/KdsHtml";

const cameraPositions: Record<ConfianceCameraTypes, [number, number, number, number, number, number]> = {
    frame: [-15, 5.5, -4, -15, 5.5, -10],
    tv: [-4, 6.5, -4, -4, 6.5, -10],
    kiosk: [3.5, 6, -5, 3.5, 0, -10],
    kds: [11.5, 5, -3.5, 11.5, 0, -10],
};

export function ConfianceLabsScene(props: any) {
    const { nodes, materials }: any = useGLTF("/model/confiancelabs/confiancelabs_model.gltf");
    const cameraControls = useRef<CameraControls>(null);

    const currentCamera = useConfianceStore((state) => state.currentCamera);

    const frameTexture = useTexture("/texture/confiancelabs/frame_bake.png");
    const tvTexture = useTexture("/texture/confiancelabs/tv_baked.png");
    const tableTexture = useTexture("/texture/confiancelabs/table_baked.png");
    const kdsTexture = useTexture("/texture/confiancelabs/kds_bake.webp");
    const wallTexture = useTexture("/texture/confiancelabs/wall_bake.png");

    const frameMaterial = useMemo(() => {
        const texture = frameTexture.clone();
        texture.flipY = false;
        texture.colorSpace = THREE.SRGBColorSpace;

        return new THREE.MeshStandardMaterial({
            map: texture,
        });
    }, [frameTexture]);

    const tvMaterial = useMemo(() => {
        const texture = tvTexture.clone();
        texture.flipY = false;
        texture.colorSpace = THREE.SRGBColorSpace;

        return new THREE.MeshStandardMaterial({
            map: texture,
        });
    }, [tvTexture]);

    const tableMaterial = useMemo(() => {
        const texture = tableTexture.clone();
        texture.flipY = false;
        texture.colorSpace = THREE.SRGBColorSpace;

        return new THREE.MeshStandardMaterial({
            map: texture,
        });
    }, [tableTexture]);

    const kdsMaterial = useMemo(() => {
        const texture = kdsTexture.clone();
        texture.flipY = false;
        texture.colorSpace = THREE.SRGBColorSpace;

        return new THREE.MeshStandardMaterial({
            map: texture,
        });
    }, [kdsTexture]);

    const wallMaterial = useMemo(() => {
        const texture = wallTexture.clone();
        texture.flipY = false;
        texture.colorSpace = THREE.SRGBColorSpace;

        return new THREE.MeshStandardMaterial({
            map: texture,
        });
    }, [wallTexture]);

    useEffect(() => {
        if (cameraControls.current) {
            cameraControls.current.setLookAt(-15, 5.5, -4, -15, 5.5, -10);
        }
    }, []);

    useEffect(() => {
        if (cameraControls.current) {
            cameraControls.current.setLookAt(...cameraPositions[currentCamera], true);
        }
    }, [currentCamera]);

    return (
        <>
            <group
                {...props}
                rotation={[0, angle(180), 0]}
                dispose={null}
            >
                <mesh
                    name="wall"
                    geometry={nodes.wall.geometry}
                    material={wallMaterial}
                    position={[0.106, 0.03, -0.176]}
                    scale={[19.458, 7.887, 7.887]}
                />
                <mesh
                    name="frame"
                    geometry={nodes.frame.geometry}
                    material={frameMaterial}
                    position={[14.981, 5.685, 7.611]}
                    rotation={[Math.PI / 2, 0, 0]}
                    scale={[0.167, 0.157, 0.152]}
                />
                <mesh position={[14.981, 5.685, 7.611]} scale={[1, 1, 1]}>
                    <planeGeometry args={[3, 4.6]} />
                    <meshStandardMaterial color="#ffffff" side={THREE.DoubleSide} transparent opacity={0} />
                    <FrameHtml />
                </mesh>
                <mesh
                    name="tv"
                    geometry={nodes.tv.geometry}
                    material={tvMaterial}
                    position={[4, 6.847, 7.402]}
                    scale={[2.833, 1.529, 0.147]}
                />
                <mesh position={[4, 6.847, 7.3]} scale={[1, 1, 1]}>
                    <planeGeometry args={[5.5, 3]} />
                    <meshStandardMaterial color="black" side={THREE.DoubleSide} />
                    <TvHtml />
                </mesh>
                <mesh
                    name="kiosk"
                    geometry={nodes.kiosk.geometry}
                    material={materials.kiosk}
                    position={[-3.722, -0.011, 6.118]}
                    rotation={[Math.PI, 0, Math.PI]}
                    scale={4.269}
                />
                <mesh position={[-3.722, 4.4, 5.87]} scale={[1, 1, 1]} rotation={[angle(40), 0, 0]}>
                    <planeGeometry args={[1.4, 1.7]} />
                    <meshStandardMaterial color="black" side={THREE.DoubleSide} />
                    <KioskHtml />
                </mesh>
                <mesh
                    name="table"
                    geometry={nodes.table.geometry}
                    material={tableMaterial}
                    position={[-11.725, 0.028, 4.95]}
                    rotation={[0, 1.571, 0]}
                    scale={0.315}
                />
                <mesh
                    name="kds"
                    geometry={nodes.kds.geometry}
                    material={kdsMaterial}
                    position={[-11.697, 3.375, 4.981]}
                    scale={[1, 0.057, 1]}
                />
                <mesh position={[-11.697, 3.45, 4.98]} scale={[1, 1, 1]} rotation={[angle(46.35), 0, 0]}>
                    <planeGeometry args={[1.8, 1.9]} />
                    <meshStandardMaterial color="black" side={THREE.DoubleSide} />
                    <KdsHtml />
                </mesh>
            </group>
            <CameraControls
                smoothTime={1}
                makeDefault
                ref={cameraControls}
                enabled={false}
            />
        </>
    );
}

useGLTF.preload("/model/confiancelabs/confiancelabs_model.gltf");
