import type { Metadata } from "next";
import "./globals.css";
import { Poller_One, Great_Vibes } from "next/font/google";
import { cn } from "@/utils/classNames";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const pollerOne = Poller_One({
  subsets: ["latin"],
  weight: ["400"],
  variable: "--font-poller-one",
});

const greatVibes = Great_Vibes({
  subsets: ["latin"],
  weight: ["400"],
  variable: "--font-great-vibes",
});
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn(pollerOne.variable, greatVibes.variable, "font-sans")}>
        <div>{children}</div>
      </body>
    </html>
  );
}
