import type { Metadata } from "next";
import "./globals.css";
import { Oswald } from "next/font/google";
import LenisProvider from "./_components/LenisProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const oswald = Oswald({
  subsets: ["latin"],
  weight: ["200", "300", "400", "500", "600", "700"],
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={oswald.className}>
        <div>{children}</div>
      </body>
    </html>
  );
}
