/* eslint-disable @typescript-eslint/no-explicit-any */
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./public/model/thirty-days/30days.gltf -k 
*/

import { CameraControls, useGLTF, useTexture } from "@react-three/drei";
import * as THREE from "three";
import { useMemo } from "react";
import { FirstMonitorHtml } from "./FirstMonitorHtml";
import { SecondMonitorHtml } from "./SecondMonitorHtml";
import { angle } from "@/utils/angle";

export function ThirtyDaysModel(props: any) {
    const { nodes, materials }: any = useGLTF("/model/thirty-days/30days.gltf");

    const wallTexture = useTexture("/texture/thirty-days/wall_bake.png");
    const windowTexture = useTexture("/texture/thirty-days/window_bake.png");
    const bgTexture = useTexture("/texture/thirty-days/bg.webp");
    const deskTopTexture = useTexture("/texture/thirty-days/table_top_bake.png");
    const deskLegTexture = useTexture("/texture/thirty-days/table_leg_bake.png");
    const monitorTexture = useTexture("/texture/thirty-days/monitor_bake.png");

    const monitorMaterial = useMemo(() => {
        const texture = monitorTexture.clone();
        texture.flipY = false;
        texture.colorSpace = THREE.SRGBColorSpace;
        return new THREE.MeshStandardMaterial({
            map: texture,
        });
    }, [monitorTexture]);

    const deskTopMaterial = useMemo(() => {
        const texture = deskTopTexture.clone();
        texture.flipY = false;
        texture.colorSpace = THREE.SRGBColorSpace;
        return new THREE.MeshStandardMaterial({
            map: texture,
        });
    }, [deskTopTexture]);

    const deskLegMaterial = useMemo(() => {
        const texture = deskLegTexture.clone();
        texture.flipY = false;
        texture.colorSpace = THREE.SRGBColorSpace;
        return new THREE.MeshStandardMaterial({
            map: texture,
        });
    }, [deskLegTexture]);
    const wallMaterial = useMemo(() => {
        const texture = wallTexture.clone();
        texture.flipY = false;
        texture.colorSpace = THREE.SRGBColorSpace;
        return new THREE.MeshStandardMaterial({
            map: texture,
        });
    }, [wallTexture]);

    const windowMaterial = useMemo(() => {
        const texture = windowTexture.clone();
        texture.flipY = false;
        texture.colorSpace = THREE.SRGBColorSpace;
        return new THREE.MeshStandardMaterial({
            map: texture,
            side: THREE.DoubleSide,
            transparent: true,
        });
    }, [windowTexture]);

    const bgMaterial = useMemo(() => {
        const texture = bgTexture.clone();
        texture.flipY = false;
        texture.colorSpace = THREE.SRGBColorSpace;
        return new THREE.MeshStandardMaterial({
            map: texture,
            side: THREE.DoubleSide,
        });
    }, [bgTexture]);

    const macbookMaterial = useMemo(() => {
        return new THREE.MeshStandardMaterial({
            color: "#1c2024",
        });
    }, []);

    return (
        <>
            <group
                rotation={[0, angle(180), 0]}
                position={[0, -3.5, 6.5]}
                {...props}
                dispose={null}>
                <mesh
                    position={[-2.18, 3.50, 5.65]}
                    rotation={[angle(190), angle(12), angle(-2)]}>
                    <planeGeometry args={[2.34, 1.42]} />
                    <meshStandardMaterial
                        color="black"
                        side={THREE.DoubleSide}
                        transparent
                        opacity={0.3}
                    />
                    <FirstMonitorHtml />
                </mesh>
                <group
                    name="monitor"
                    position={[-0.769, 0.063, 5.455]}
                    rotation={[Math.PI / 2, 0, -2.927]}
                    scale={0.038}>
                    <group
                        name="Meshes"
                        position={[395.452, 844.683, 0]}
                        scale={100}>
                        <group
                            name="Sketchfab_model"
                            rotation={[-Math.PI / 2, 0, 0]}
                            scale={1.907}>
                            <group
                                name="Plane001_1"
                                position={[-2.079, 0.464, -4.456]}
                                rotation={[1.396, 0, Math.PI]}>
                                <mesh
                                    name="Plane_0001"
                                    geometry={nodes.Plane_0001.geometry}
                                    material={materials["MinitorSilver.001"]}
                                />
                                <mesh
                                    name="Plane_0001_1"
                                    geometry={nodes.Plane_0001_1.geometry}
                                    material={monitorMaterial}
                                />
                                <mesh
                                    name="Plane_0001_2"
                                    geometry={nodes.Plane_0001_2.geometry}
                                    material={monitorMaterial}
                                />
                            </group>
                        </group>
                    </group>
                </group>
                <group
                    name="table"
                    position={[0.046, 0, 5.22]}
                    rotation={[Math.PI / 2, 0, Math.PI]}
                    scale={0.03}>
                    <group
                        name="Meshes003"
                        scale={100}>
                        <group
                            name="comp_desk_remote_1001"
                            rotation={[Math.PI / 2, 0, 0]}>
                            <mesh
                                name="Object_4001"
                                geometry={nodes.Object_4001.geometry}
                                material={materials["comp_desk_remote.001"]}
                            />
                            <mesh
                                name="Object_5"
                                geometry={nodes.Object_5.geometry}
                                material={materials["comp_desk_2remote.001"]}
                            />
                            <mesh
                                name="Object_6001"
                                geometry={nodes.Object_6001.geometry}
                                material={materials["comp_desk_1remote.001"]}
                            />
                            <mesh
                                name="Object_7"
                                geometry={nodes.Object_7.geometry}
                                material={materials["comp_desk_button.001"]}
                            />
                        </group>
                        <group
                            name="leg"
                            rotation={[Math.PI / 2, 0, 0]}>
                            <mesh
                                name="object"
                                geometry={nodes.object.geometry}
                                material={deskLegMaterial}
                            />
                            <mesh
                                name="Object_0002"
                                geometry={nodes.Object_0002.geometry}
                                material={deskLegMaterial}
                            />
                            <mesh
                                name="Object_2002"
                                geometry={nodes.Object_2002.geometry}
                                material={deskLegMaterial}
                            />
                            <mesh
                                name="Object_3002"
                                geometry={nodes.Object_3002.geometry}
                                material={deskLegMaterial}
                            />
                        </group>
                        <mesh
                            name="table_top"
                            geometry={nodes.table_top.geometry}
                            material={deskTopMaterial}
                        />
                    </group>
                </group>
                <mesh
                    position={[1.05, 2.75, 5.58]}
                    rotation={[angle(200.9), angle(-12), angle(4.5)]}>
                    <planeGeometry args={[1.36, 0.88]} />
                    <meshStandardMaterial
                        color="black"
                        side={THREE.DoubleSide}
                        transparent
                        opacity={0.3}
                    />
                    <SecondMonitorHtml />
                </mesh>
                <group
                    name="macbook"
                    position={[0.899, 2.273, 4.927]}
                    rotation={[Math.PI / 2, 0, 2.911]}
                    scale={0.045}>

                    <mesh
                        name="AQdtiiJfiakvCKx"
                        geometry={nodes.AQdtiiJfiakvCKx.geometry}
                        material={macbookMaterial}
                    />
                    <mesh
                        name="cdsXAgNBwwCPrIE"
                        geometry={nodes.cdsXAgNBwwCPrIE.geometry}
                        material={macbookMaterial}
                    />
                    <mesh
                        name="UcEDhfwzyyGMEfj"
                        geometry={nodes.UcEDhfwzyyGMEfj.geometry}
                        material={macbookMaterial}
                    />
                    <mesh
                        name="DmUcWNXfiLPcftc"
                        geometry={nodes.DmUcWNXfiLPcftc.geometry}
                        material={macbookMaterial}
                    />
                    <mesh
                        name="ELAWKPIQpGuqYuU"
                        geometry={nodes.ELAWKPIQpGuqYuU.geometry}
                        material={macbookMaterial}
                    />
                    <mesh
                        name="FmsrGmNZGtSredn"
                        geometry={nodes.FmsrGmNZGtSredn.geometry}
                        material={macbookMaterial}
                    />
                    <mesh
                        name="jbtMEbemwaBHRTw"
                        geometry={nodes.jbtMEbemwaBHRTw.geometry}
                        material={macbookMaterial}
                    />
                    <mesh
                        name="jfSniDGKVWZvpyG"
                        geometry={nodes.jfSniDGKVWZvpyG.geometry}
                        material={macbookMaterial}
                    />
                    <mesh
                        name="lZDBMTdjXPebUMa"
                        geometry={nodes.lZDBMTdjXPebUMa.geometry}
                        material={macbookMaterial}
                    />
                    <mesh
                        name="ZroMGzfQtHrkgUh"
                        geometry={nodes.ZroMGzfQtHrkgUh.geometry}
                        material={macbookMaterial}
                    />
                    <mesh
                        name="bckGBpxpLXNHmCa"
                        geometry={nodes.bckGBpxpLXNHmCa.geometry}
                        material={macbookMaterial}
                    />
                    <mesh
                        name="JXvTyELxHLGtnWp"
                        geometry={nodes.JXvTyELxHLGtnWp.geometry}
                        material={macbookMaterial}
                    />
                    <mesh
                        name="cpUmMDYlGqLEAMt"
                        geometry={nodes.cpUmMDYlGqLEAMt.geometry}
                        material={macbookMaterial}
                    />
                    <mesh
                        name="sIzFavpnYbDfLWk"
                        geometry={nodes.sIzFavpnYbDfLWk.geometry}
                        material={macbookMaterial}
                    />
                    <mesh
                        name="sonZrhRIQDlQHcy"
                        geometry={nodes.sonZrhRIQDlQHcy.geometry}
                        material={macbookMaterial}
                    />
                    <mesh
                        name="IJeReHnhQHJFtgB"
                        geometry={nodes.IJeReHnhQHJFtgB.geometry}
                        material={macbookMaterial}
                    />
                    <mesh
                        name="lzNeOaWQWAReGok"
                        geometry={nodes.lzNeOaWQWAReGok.geometry}
                        material={macbookMaterial}
                    />
                    <mesh
                        name="WZqbfOdYdlPMpRs"
                        geometry={nodes.WZqbfOdYdlPMpRs.geometry}
                        material={macbookMaterial}
                    />
                    <mesh
                        name="aBJxhjUzVIkBmJN"
                        geometry={nodes.aBJxhjUzVIkBmJN.geometry}
                        material={macbookMaterial}
                    />
                    <mesh
                        name="mTDvrHXNRqkIrBd"
                        geometry={nodes.mTDvrHXNRqkIrBd.geometry}
                        material={macbookMaterial}
                    />
                    <mesh
                        name="fVNvUQeYMdbMNOA"
                        geometry={nodes.fVNvUQeYMdbMNOA.geometry}
                        material={macbookMaterial}
                    />
                    <mesh
                        name="WzbwnVztmigkRgn"
                        geometry={nodes.WzbwnVztmigkRgn.geometry}
                        material={
                            new THREE.MeshStandardMaterial({
                                color: "#2d3338",
                            })
                        }
                    />
                    <mesh
                        name="bzDyZTvUFAEJLcq"
                        geometry={nodes.bzDyZTvUFAEJLcq.geometry}
                        material={macbookMaterial}
                    />
                    <mesh
                        name="dAVNlHAHYLbkxrB"
                        geometry={nodes.dAVNlHAHYLbkxrB.geometry}
                        material={macbookMaterial}
                    />
                    <mesh
                        name="EBRhBFNqcMTaWWv"
                        geometry={nodes.EBRhBFNqcMTaWWv.geometry}
                        material={macbookMaterial}
                    />
                    <mesh
                        name="wyClPAIazRlKQnt"
                        geometry={nodes.wyClPAIazRlKQnt.geometry}
                        material={
                            new THREE.MeshStandardMaterial({
                                color: "#c5c5c5",
                            })
                        }
                    />
                    <mesh
                        name="QSjoCOCzvxPnLpK"
                        geometry={nodes.QSjoCOCzvxPnLpK.geometry}
                        material={macbookMaterial}
                    />
                    <mesh
                        name="LBeBZdkKmrJVhJd"
                        geometry={nodes.LBeBZdkKmrJVhJd.geometry}
                        material={macbookMaterial}
                    />
                    <mesh
                        name="MwJmMcLbTBwQpxl"
                        geometry={nodes.MwJmMcLbTBwQpxl.geometry}
                        material={macbookMaterial}
                    />
                    <mesh
                        name="OCxZAMeEkQKexHA"
                        geometry={nodes.OCxZAMeEkQKexHA.geometry}
                        material={macbookMaterial}
                    />
                    <mesh
                        name="XodVrcYKiUPGCmX"
                        geometry={nodes.XodVrcYKiUPGCmX.geometry}
                        material={macbookMaterial}
                    />
                    <mesh
                        name="JNlPAPsywCtwJrd"
                        geometry={nodes.JNlPAPsywCtwJrd.geometry}
                        material={macbookMaterial}
                    />
                    <mesh
                        name="KjpcUkkMjGYeXkV"
                        geometry={nodes.KjpcUkkMjGYeXkV.geometry}
                        material={macbookMaterial}
                    />
                    <mesh
                        name="UEFeUEhkJPdlgXF"
                        geometry={nodes.UEFeUEhkJPdlgXF.geometry}
                        material={macbookMaterial}
                    />
                    <mesh
                        name="xiLiwJHfkqIwaTs"
                        geometry={nodes.xiLiwJHfkqIwaTs.geometry}
                        material={macbookMaterial}
                    />
                    <mesh
                        name="LQtuXuSGFKsUXjP"
                        geometry={nodes.LQtuXuSGFKsUXjP.geometry}
                        material={macbookMaterial}
                    />
                    <mesh
                        name="nAIWMiVEtSYdjdZ_1"
                        geometry={nodes.nAIWMiVEtSYdjdZ_1.geometry}
                        material={macbookMaterial}
                    />
                    <mesh
                        name="nAIWMiVEtSYdjdZ_2"
                        geometry={nodes.nAIWMiVEtSYdjdZ_2.geometry}
                        material={macbookMaterial}
                    />
                    <mesh
                        name="nAIWMiVEtSYdjdZ_3"
                        geometry={nodes.nAIWMiVEtSYdjdZ_3.geometry}
                        material={macbookMaterial}
                    />
                    <mesh
                        name="nAIWMiVEtSYdjdZ_4"
                        geometry={nodes.nAIWMiVEtSYdjdZ_4.geometry}
                        material={
                            new THREE.MeshStandardMaterial({
                                color: "#000000",
                            })
                        }
                    />
                    <mesh
                        name="nAIWMiVEtSYdjdZ_5"
                        geometry={nodes.nAIWMiVEtSYdjdZ_5.geometry}
                        material={macbookMaterial}
                    />
                    <mesh
                        name="nAIWMiVEtSYdjdZ_6"
                        geometry={nodes.nAIWMiVEtSYdjdZ_6.geometry}
                        material={macbookMaterial}
                    />
                    <mesh
                        name="nAIWMiVEtSYdjdZ_7"
                        geometry={nodes.nAIWMiVEtSYdjdZ_7.geometry}
                        material={materials.HlQwFCAPWzetDQy}
                    />
                    <mesh
                        name="nAIWMiVEtSYdjdZ_8"
                        geometry={nodes.nAIWMiVEtSYdjdZ_8.geometry}
                        material={macbookMaterial}
                    />
                </group>
                <mesh
                    name="glass"
                    geometry={nodes.glass.geometry}
                    material={windowMaterial}
                    position={[0, 4.453, 6.645]}
                    rotation={[Math.PI / 2, 0, 0]}
                    scale={[3.551, 2.079, 2.186]}
                />
                <mesh
                    name="window"
                    geometry={nodes.window.geometry}
                    material={wallMaterial}
                    scale={6.452}
                />
                <mesh
                    name="bg001"
                    geometry={nodes.bg001.geometry}
                    material={bgMaterial}
                    position={[1.369, 3.931, 8.353]}
                    rotation={[Math.PI / 2, 0, 0]}
                    scale={8.326}
                />
            </group>
            <CameraControls />
        </>
    );
}

useGLTF.preload("/model/thirty-days/30days.gltf");
