/* eslint-disable @typescript-eslint/no-explicit-any */
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./public/model/ispg/ispg_phone.gltf -k 
*/

import { CameraControls, Environment, useGLTF, useTexture } from "@react-three/drei";
import { useEffect, useMemo, useRef } from "react";
import { PhoneHtml } from "./PhoneHtml";
import * as THREE from "three";
import { angle } from "@/utils/angle";

export function IspgModel(props: any) {
    const { nodes, materials }: any = useGLTF("/model/ispg/ispg_phone.gltf");
    const cameraControls = useRef<CameraControls>(null);
    const tableTexture = useTexture("/texture/ispg/table.png");

    const tableMaterial = useMemo(() => {
        const texture = tableTexture.clone();
        texture.flipY = false;
        texture.colorSpace = THREE.SRGBColorSpace;

        return new THREE.MeshStandardMaterial({
            map: texture,
        });
    }, [tableTexture]);
    useEffect(() => {
        if (cameraControls.current) {
            cameraControls.current.setLookAt(0, 2.5, 0, 0, 0, -0.5, true);
        }
    }, []);

    return (
        <>
            <group
                {...props}
                position={[0.1, 0, 0]}
                rotation={[0, -angle(90), 0]}
                scale={0.2}
                dispose={null}>
                <mesh
                    name="Table_Large_Rectangular_01_Circle004"
                    geometry={nodes.Table_Large_Rectangular_01_Circle004.geometry}
                    material={tableMaterial}
                />
                <group
                    name="mobile"
                    rotation={[Math.PI / 2, 0, 0]}>
                    <mesh
                        name="Torx_Flat_Top010"
                        geometry={nodes.Torx_Flat_Top010.geometry}
                        material={materials.Side_Dark_Lines}
                    />
                    <mesh
                        name="Torx_Flat_Top010_1"
                        geometry={nodes.Torx_Flat_Top010_1.geometry}
                        material={materials["Side_Dark_Lines.003"]}
                    />
                    <mesh
                        name="Torx_Flat_Top010_2"
                        geometry={nodes.Torx_Flat_Top010_2.geometry}
                        material={materials.Matte_Metallic_Blue}
                    />
                    <mesh
                        name="Torx_Flat_Top010_3"
                        geometry={nodes.Torx_Flat_Top010_3.geometry}
                        material={materials.LIDAR_Senser}
                    />
                    <mesh
                        name="Torx_Flat_Top010_4"
                        geometry={nodes.Torx_Flat_Top010_4.geometry}
                        material={materials.Torch}
                    />
                    <mesh
                        name="Torx_Flat_Top010_5"
                        geometry={nodes.Torx_Flat_Top010_5.geometry}
                        material={materials["Matte_Metallic_Blue_logo.001"]}
                    />
                    <mesh
                        name="Torx_Flat_Top010_6"
                        geometry={nodes.Torx_Flat_Top010_6.geometry}
                        material={materials.Display_Blue}
                    />
                    <mesh
                        name="Torx_Flat_Top010_7"
                        geometry={nodes.Torx_Flat_Top010_7.geometry}
                        material={materials.Mic}
                    />
                    <mesh
                        name="Torx_Flat_Top010_8"
                        geometry={nodes.Torx_Flat_Top010_8.geometry}
                        material={materials.Side_Strips_Blue}
                    />
                    <mesh
                        name="Torx_Flat_Top010_9"
                        geometry={nodes.Torx_Flat_Top010_9.geometry}
                        material={materials.Warnex_Black}
                    />
                    <mesh
                        name="Torx_Flat_Top010_10"
                        geometry={nodes.Torx_Flat_Top010_10.geometry}
                        material={materials.Display_Borders}
                    />
                    <mesh
                        name="Torx_Flat_Top010_11"
                        geometry={nodes.Torx_Flat_Top010_11.geometry}
                        material={nodes.Torx_Flat_Top010_11.material}
                    />
                    <mesh
                        name="Torx_Flat_Top010_12"
                        geometry={nodes.Torx_Flat_Top010_12.geometry}
                        material={materials.Metal_Mesh_Grill}
                    />
                </group>
            </group>
            <mesh
                position={[-0.015, 1.58, -0.016]}
                rotation={[angle(90), 0, angle(-1)]}>
                <planeGeometry args={[0.37, 0.79]} />
                {/* <meshStandardMaterial color="transparent" side={THREE.DoubleSide} /> */}
                <PhoneHtml />
            </mesh>
            <Environment preset="apartment" />
        </>
    );
}

useGLTF.preload("/model/ispg/ispg_phone.gltf");
