/* eslint-disable @typescript-eslint/no-explicit-any */
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./public/model/ispg/ispg_phone.gltf -k 
*/

import { Environment, useGLTF, useTexture } from "@react-three/drei";
import { useMemo } from "react";
import { PhoneHtml } from "./PhoneHtml";
import * as THREE from "three";
import { angle } from "@/utils/angle";

export function IspgModel() {
    const { nodes, materials }: any = useGLTF("/model/ispg/ispg_phone.glb");
    const tableTexture = useTexture("/texture/ispg/table.webp");

    const tableMaterial = useMemo(() => {
        const texture = tableTexture.clone();
        texture.flipY = false;
        texture.colorSpace = THREE.SRGBColorSpace;

        return new THREE.MeshStandardMaterial({
            map: texture,
        });
    }, [tableTexture]);

    return (
        <>
            <group
                position={[0.1, 0, 0]}
                rotation={[0, -angle(90), 0]}
                scale={0.2}
                dispose={null}>
                <mesh
                    name="Table_Large_Rectangular_01_Circle004"
                    geometry={nodes.Table_Large_Rectangular_01_Circle004.geometry}
                    material={tableMaterial}
                />
                <group
                    name="mobile"
                    rotation={[Math.PI / 2, 0, 0]}>
                    <mesh
                        name="Torx_Flat_Top010"
                        geometry={nodes.Torx_Flat_Top010.geometry}
                        material={materials.Side_Dark_Lines}
                    />
                    <mesh
                        name="Torx_Flat_Top010_1"
                        geometry={nodes.Torx_Flat_Top010_1.geometry}
                        material={materials["Side_Dark_Lines.003"]}
                    />
                    <mesh
                        name="Torx_Flat_Top010_2"
                        geometry={nodes.Torx_Flat_Top010_2.geometry}
                        material={materials.Matte_Metallic_Blue}
                    />
                    <mesh
                        name="Torx_Flat_Top010_3"
                        geometry={nodes.Torx_Flat_Top010_3.geometry}
                        material={materials.LIDAR_Senser}
                    />
                    <mesh
                        name="Torx_Flat_Top010_4"
                        geometry={nodes.Torx_Flat_Top010_4.geometry}
                        material={materials.Torch}
                    />
                    <mesh
                        name="Torx_Flat_Top010_5"
                        geometry={nodes.Torx_Flat_Top010_5.geometry}
                        material={materials["Matte_Metallic_Blue_logo.001"]}
                    />
                    <mesh
                        name="Torx_Flat_Top010_6"
                        geometry={nodes.Torx_Flat_Top010_6.geometry}
                        material={materials.Display_Blue}
                    />
                    <mesh
                        name="Torx_Flat_Top010_7"
                        geometry={nodes.Torx_Flat_Top010_7.geometry}
                        material={materials.Mic}
                    />
                    <mesh
                        name="Torx_Flat_Top010_8"
                        geometry={nodes.Torx_Flat_Top010_8.geometry}
                        material={materials.Side_Strips_Blue}
                    />
                    <mesh
                        name="Torx_Flat_Top010_9"
                        geometry={nodes.Torx_Flat_Top010_9.geometry}
                        material={materials.Warnex_Black}
                    />
                    <mesh
                        name="Torx_Flat_Top010_10"
                        geometry={nodes.Torx_Flat_Top010_10.geometry}
                        material={materials.Display_Borders}
                    />
                    <mesh
                        name="Torx_Flat_Top010_11"
                        geometry={nodes.Torx_Flat_Top010_11.geometry}
                        material={nodes.Torx_Flat_Top010_11.material}
                    />
                    <mesh
                        name="Torx_Flat_Top010_12"
                        geometry={nodes.Torx_Flat_Top010_12.geometry}
                        material={materials.Metal_Mesh_Grill}
                    />

                    {/* PhoneHtml mesh - Adjusted position and size */}
                    <mesh
                        position={[0, 0.5, -8]}
                        rotation={[0, 0, angle(90)]}>
                        <planeGeometry args={[1.85, 3.9]} />
                        <PhoneHtml />
                    </mesh>
                </group>
            </group>
            <Environment preset="apartment" />
        </>
    );
}

useGLTF.preload("/model/ispg/ispg_phone.glb");
